# Generated by Django 4.1.3 on 2022-12-01 21:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_sub_title_en_news_sub_title_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('sub_title', models.CharField(max_length=255, verbose_name='sub title')),
                ('sub_title_uz', models.CharField(max_length=255, null=True, verbose_name='sub title')),
                ('sub_title_ru', models.CharField(max_length=255, null=True, verbose_name='sub title')),
                ('sub_title_en', models.CharField(max_length=255, null=True, verbose_name='sub title')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text')),
            ],
            options={
                'verbose_name': 'Static Page ',
                'verbose_name_plural': 'Static Pages',
                'db_table': 'static_page',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text'),
        ),
    ]
