# Generated by Django 4.1.3 on 2022-12-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_staticpage_news_text_news_text_en_news_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Static Page ', 'verbose_name_plural': 'Static Pages'},
        ),
    ]
