# Generated by Django 4.1.3 on 2022-12-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu_title_en_menu_title_ru_menu_title_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('icon', models.ImageField(upload_to='statistic/icon/', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Partner ',
                'verbose_name_plural': 'Partner',
                'db_table': 'partner',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('sub_title', models.CharField(max_length=255, verbose_name='sub_title')),
                ('sub_title_uz', models.CharField(max_length=255, null=True, verbose_name='sub_title')),
                ('sub_title_ru', models.CharField(max_length=255, null=True, verbose_name='sub_title')),
                ('sub_title_en', models.CharField(max_length=255, null=True, verbose_name='sub_title')),
                ('image', models.ImageField(upload_to='slider/image/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Slider ',
                'verbose_name_plural': 'Sliders',
                'db_table': 'slider',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('icon', models.ImageField(upload_to='statistic/icon/', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Statistic ',
                'verbose_name_plural': 'Statistics',
                'db_table': 'statistic',
                'ordering': ('order',),
            },
        ),
    ]
