# Generated by Django 4.1.3 on 2022-12-01 22:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_partner_slider_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sub_title', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'About Us ',
                'verbose_name_plural': "About Us'",
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('image', models.ImageField(upload_to='certificate/images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Certificate ',
                'verbose_name_plural': 'Certificates',
                'db_table': 'certificate',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CompanyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sub_title', models.CharField(max_length=255, verbose_name='sub_title')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'CompanyCertificate ',
                'verbose_name_plural': 'CompanyCertificates',
                'db_table': 'company_certificate',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('icon', models.ImageField(upload_to='contact/icons/', verbose_name='icon')),
                ('contact', models.CharField(max_length=255, verbose_name='contact')),
            ],
            options={
                'verbose_name': 'Contact ',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('icon', models.ImageField(upload_to='social_media/icons/', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'SocialMedia ',
                'verbose_name_plural': 'SocialMedias',
                'db_table': 'social_media',
                'ordering': ('order',),
            },
        ),
    ]
