# Generated by Django 4.1.3 on 2022-12-01 23:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutus_certificate_companycertificate_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='text_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
