# Generated by Django 4.1.3 on 2022-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutus_title_en_aboutus_title_ru_aboutus_title_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us ', 'verbose_name_plural': '5 About Us'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('order',), 'verbose_name': 'Certificate ', 'verbose_name_plural': '7 Certificates'},
        ),
        migrations.AlterModelOptions(
            name='companycertificate',
            options={'verbose_name': 'CompanyCertificate ', 'verbose_name_plural': '6 CompanyCertificates'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('order',), 'verbose_name': 'Contact ', 'verbose_name_plural': '9 Contacts'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('order',), 'verbose_name': 'Menu ', 'verbose_name_plural': '1 Menus'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('order',), 'verbose_name': 'Partner ', 'verbose_name_plural': '4 Partners'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('order',), 'verbose_name': 'Slider ', 'verbose_name_plural': '2 Sliders'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ('order',), 'verbose_name': 'SocialMedia ', 'verbose_name_plural': '8 SocialMedias'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ('order',), 'verbose_name': 'Statistic ', 'verbose_name_plural': '3 Statistics'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='sub_title',
            field=models.CharField(max_length=255, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sub_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sub_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sub_title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
    ]
