# Generated by Django 4.1.3 on 2022-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_aboutus_options_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('order',), 'verbose_name': 'Contact ', 'verbose_name_plural': '   9 Contacts'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub_title_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub_title_ru',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub_title_uz',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
