# Generated by Django 4.1.3 on 2022-12-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_contact_options_aboutus_sub_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycertificate',
            name='sub_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sub_title'),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='sub_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='sub_title'),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='sub_title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='sub_title'),
        ),
    ]
