# Generated by Django 4.1.3 on 2022-12-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_companycertificate_sub_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycertificate',
            options={'verbose_name': 'Company Certificate ', 'verbose_name_plural': '6 Company Certificates'},
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='certificate',
            field=models.ImageField(default=1, upload_to='company_certificate/images/'),
            preserve_default=False,
        ),
    ]
