# Generated by Django 4.1.3 on 2022-12-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_companycertificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycertificate',
            name='certificate',
            field=models.ImageField(upload_to='company_certificate/images/', verbose_name='certificate'),
        ),
    ]
